ktor:
  mode:
    - dev
  application:
    modules:
      - pl.ejdev.ApplicationKt.module
  deployment:
    port: 8080
  database:
      url: "jdbc:postgresql://localhost:5432/hex"
      user: "hex"
      password: "hex"
      driver: "org.postgresql.Driver"
  jwt:
    domain: "https://jwt-provider-domain/"
    audience: "jwt-audience"
    realm: "ktor sample app"

